import type { CsvImportResponse, JsonlImportResponse, SpreadsheetRowImportResponse } from "../api/client";
import { SpreadsheetImportPanel } from "../spreadsheets/SpreadsheetImportPanel";
import { EmptyState, ProductSurface } from "../ui/ProductPrimitives";
import { CSVImportPanel } from "./CSVImportPanel";
import { JSONLImportPanel } from "./JSONLImportPanel";

type ImportWorkspaceProps = {
  jsonlCases: string;
  jsonlImportResult: JsonlImportResponse | null;
  csvCases: string;
  csvImportResult: CsvImportResponse | null;
  spreadsheetRowsJson: string;
  spreadsheetImportResult: SpreadsheetRowImportResponse | null;
  onJsonlChange: (value: string) => void;
  onCsvChange: (value: string) => void;
  onSpreadsheetRowsJsonChange: (value: string) => void;
  onImportJsonl: () => void;
  onImportCsv: () => void;
  onImportSpreadsheetRowsJson: () => void;
};

export function ImportWorkspace({
  jsonlCases,
  jsonlImportResult,
  csvCases,
  csvImportResult,
  spreadsheetRowsJson,
  spreadsheetImportResult,
  onJsonlChange,
  onCsvChange,
  onSpreadsheetRowsJsonChange,
  onImportJsonl,
  onImportCsv,
  onImportSpreadsheetRowsJson
}: ImportWorkspaceProps) {
  return (
    <div className="intake-stack" aria-label="Case intake import methods">
      <ProductSurface
        title="JSONL Import"
        eyebrow="Intake"
        description="Paste JSONL cases generated by harness collection or offline curation."
        className="import-panel"
      >
        <JSONLImportPanel
          value={jsonlCases}
          result={jsonlImportResult}
          onChange={onJsonlChange}
          onImport={onImportJsonl}
        />
        {jsonlImportResult ? null : <EmptyState title="No import result yet." description="Run an import to see accepted cases and rejected rows." />}
      </ProductSurface>
      <ProductSurface
        title="CSV Import"
        eyebrow="Intake"
        description="Paste CSV rows when evaluators export tabular badcase batches."
        className="import-panel"
      >
        <CSVImportPanel value={csvCases} result={csvImportResult} onChange={onCsvChange} onImport={onImportCsv} />
        {csvImportResult ? null : <EmptyState title="No import result yet." description="Run an import to see accepted cases and rejected rows." />}
      </ProductSurface>
      <ProductSurface
        title="Spreadsheet Rows Import"
        eyebrow="Intake"
        description="Paste Lark spreadsheet rows after sync or manual export."
        className="import-panel"
      >
        <SpreadsheetImportPanel
          value={spreadsheetRowsJson}
          result={spreadsheetImportResult}
          onChange={onSpreadsheetRowsJsonChange}
          onImport={onImportSpreadsheetRowsJson}
        />
        {spreadsheetImportResult ? null : (
          <EmptyState title="No import result yet." description="Run an import to see accepted cases and rejected rows." />
        )}
      </ProductSurface>
    </div>
  );
}
