from __future__ import annotations

from typing import Literal

LARK_BOT_SETUP_PACKAGE_URL = "/api/lark/bot/setup-package.zip"
LARK_BOT_PERMISSION_CHECKLIST_URL = "/api/lark/bot/permission-checklist"
LARK_BOT_RECEIVE_EVENT_TYPE = "im.message.receive_v1"
LARK_BOT_CARD_ACTION_EVENT_TYPE = "card.action.trigger"
LARK_BOT_LONG_CONNECTION_PROFILE = "xiaoD"
LARK_BOT_LONG_CONNECTION_RECEIVE_SCOPE = "im:message.p2p_msg:readonly"

LarkBotPermissionPhase = Literal["required_now", "recommended_next"]
LarkBotPermissionType = Literal["event_subscription", "oauth_scope"]
LarkBotPermissionRisk = Literal["event", "read", "write"]
LARK_BOT_SETUP_ITEM_KEYS = {
    "deploy_callback_url",
    "copy_verification_token",
    "copy_encrypt_key",
    "subscribe_message_event",
    "configure_card_callback",
    "grant_im_bot_scope",
    "configure_bot_identity",
    "enable_trusted_actor",
    "add_bot_to_target_chat",
    "run_webhook_probe",
}
LARK_BOT_PERMISSION_CATALOG: tuple[dict[str, object], ...] = (
    {
        "key": "event_message_receive",
        "title": "订阅消息接收事件",
        "category": "事件订阅",
        "permission_type": "event_subscription",
        "scope": LARK_BOT_RECEIVE_EVENT_TYPE,
        "phase": "required_now",
        "risk_level": "event",
        "operation": "event consume im.message.receive_v1",
        "required_for": "长连接接收用户私聊、群聊 @ 小D和消息事件。",
        "repair_hint": "在飞书开放平台事件订阅中订阅 im.message.receive_v1，并用真实消息验证长连接消费者能收到事件。",
    },
    {
        "key": "im_read_p2p",
        "title": "读取私聊消息",
        "category": "IM 读取",
        "permission_type": "oauth_scope",
        "scope": LARK_BOT_LONG_CONNECTION_RECEIVE_SCOPE,
        "phase": "required_now",
        "risk_level": "read",
        "operation": "event payload read",
        "required_for": "解析用户私聊中的自然语言、飞书链接和附件入口。",
        "repair_hint": "在飞书开放平台为小D应用开通私聊消息读取权限，并重新发布/安装应用。",
    },
    {
        "key": "im_read_group_at",
        "title": "读取群聊 @ 小D消息",
        "category": "IM 读取",
        "permission_type": "oauth_scope",
        "scope": "im:message.group_at_msg:readonly",
        "phase": "required_now",
        "risk_level": "read",
        "operation": "event payload read",
        "required_for": "解析群聊中用户 @ 小D的自然语言、飞书链接和附件入口。",
        "repair_hint": "在飞书开放平台为小D应用开通群聊 @ 机器人消息事件读取权限，并重新发布/安装应用。",
    },
    {
        "key": "im_send_as_bot",
        "title": "机器人发送消息",
        "category": "IM 回复",
        "permission_type": "oauth_scope",
        "scope": "im:message:send_as_bot",
        "phase": "required_now",
        "risk_level": "write",
        "operation": "im +messages-reply / +messages-send",
        "required_for": "小D回复待确认、权限缺失、任务状态和报告链接。",
        "repair_hint": "在飞书开放平台为应用开通机器人发送消息权限，并确认机器人已加入目标会话。",
    },
    {
        "key": "im_read_group_at_include_bot",
        "title": "读取群内其他机器人 @ 小D消息",
        "category": "IM 读取",
        "permission_type": "oauth_scope",
        "scope": "im:message.group_at_msg.include_bot:readonly",
        "phase": "recommended_next",
        "risk_level": "read",
        "operation": "event payload read",
        "required_for": "允许开发 bot 或群内其他机器人 @ 小D时也触发接收消息事件，用于自动化 dogfood。",
        "repair_hint": "若需要用开发 bot 代替真实用户做群聊 dogfood，在飞书开放平台开通该 include_bot 权限并重新发布应用。",
    },
    {
        "key": "sheet_read",
        "title": "读取飞书表格",
        "category": "表格读取",
        "permission_type": "oauth_scope",
        "scope": "sheets:spreadsheet:readonly",
        "phase": "required_now",
        "risk_level": "read",
        "operation": "sheets +csv-get / +cells-get",
        "required_for": "读取表格行、表头映射、富文本附件 token和 badcase 字段。",
        "repair_hint": "在飞书开放平台开通电子表格读取权限，确保小D可访问目标表格。",
    },
    {
        "key": "sheet_media_download",
        "title": "下载表格附件",
        "category": "表格附件下载",
        "permission_type": "oauth_scope",
        "scope": "docs:document.media:download",
        "phase": "required_now",
        "risk_level": "read",
        "operation": "api GET /drive/v1/medias/:file_token/download",
        "required_for": "下载表格单元格里的视频/图片附件，生成真实 Debug 媒体输入。",
        "repair_hint": "在飞书开放平台开通“下载文档中的图片和文件”权限，并让小D重新安装或刷新授权后重试表格链接。",
    },
    {
        "key": "sheet_writeback",
        "title": "写回飞书表格",
        "category": "表格写回",
        "permission_type": "oauth_scope",
        "scope": "sheets:spreadsheet",
        "phase": "recommended_next",
        "risk_level": "write",
        "operation": "sheets +cells-set",
        "required_for": "调试完成后写回状态、根因、报告链接和推荐操作。",
        "repair_hint": "开通电子表格编辑权限；写操作仍需 Debug Agent 写入确认门禁。",
    },
    {
        "key": "doc_read",
        "title": "读取飞书文档",
        "category": "文档读取",
        "permission_type": "oauth_scope",
        "scope": "docx:document:readonly",
        "phase": "recommended_next",
        "risk_level": "read",
        "operation": "docs +fetch --api-version v2",
        "required_for": "读取用户发来的文档正文并提取 badcase 信息。",
        "repair_hint": "开通新版文档读取权限，并确保文档对小D应用可见。",
    },
    {
        "key": "drive_file_read",
        "title": "读取云盘文件元信息",
        "category": "云盘读取",
        "permission_type": "oauth_scope",
        "scope": "drive:file:readonly",
        "phase": "recommended_next",
        "risk_level": "read",
        "operation": "drive file metadata/read",
        "required_for": "识别用户发送的云盘文件类型、文件名和资源可访问性。",
        "repair_hint": "开通云空间文件读取权限，和下载权限一起覆盖附件处理。",
    },
    {
        "key": "drive_file_download",
        "title": "下载云盘普通文件",
        "category": "云盘下载",
        "permission_type": "oauth_scope",
        "scope": "drive:file:download",
        "phase": "recommended_next",
        "risk_level": "read",
        "operation": "drive +download",
        "required_for": "下载用户直接发送的云盘普通文件链接。",
        "repair_hint": "开通云空间文件下载权限，用于非表格附件的普通云盘文件输入。",
    },
    {
        "key": "drive_metadata_read",
        "title": "读取云盘元数据",
        "category": "云盘读取",
        "permission_type": "oauth_scope",
        "scope": "drive:drive.metadata:readonly",
        "phase": "recommended_next",
        "risk_level": "read",
        "operation": "drive metadata read",
        "required_for": "定位云盘资源、父目录和权限状态。",
        "repair_hint": "开通云空间元数据读取权限，用于链接和附件诊断。",
    },
    {
        "key": "base_read",
        "title": "读取多维表格",
        "category": "Base 读取",
        "permission_type": "oauth_scope",
        "scope": "bitable:app:readonly",
        "phase": "recommended_next",
        "risk_level": "read",
        "operation": "base +table-list / +record-list",
        "required_for": "读取 Base 表、记录和字段并生成 badcase 草稿。",
        "repair_hint": "开通多维表格只读权限，并确保小D可访问目标 Base。",
    },
    {
        "key": "doc_write",
        "title": "生成飞书文档报告",
        "category": "文档写入",
        "permission_type": "oauth_scope",
        "scope": "docx:document",
        "phase": "recommended_next",
        "risk_level": "write",
        "operation": "docx document create/update",
        "required_for": "把调试结论沉淀为飞书文档报告。",
        "repair_hint": "开通新版文档写权限；生成文档前仍需写操作确认。",
    },
    {
        "key": "base_write",
        "title": "写回多维表格",
        "category": "Base 写入",
        "permission_type": "oauth_scope",
        "scope": "bitable:app",
        "phase": "recommended_next",
        "risk_level": "write",
        "operation": "base record update",
        "required_for": "把任务状态、根因和报告链接写回 Base 台账。",
        "repair_hint": "开通多维表格写权限；写回前仍需确认风险动作。",
    },
)
